/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as RestaurantIRouteImport } from './routes/restaurant.$i'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerReviewsRouteImport } from './routes/owner.reviews'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as OwnerNotificationsRouteImport } from './routes/owner.notifications'
import { Route as OwnerMenuRouteImport } from './routes/owner.menu'
import { Route as OwnerCouponsRouteImport } from './routes/owner.coupons'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as InvoiceIRouteImport } from './routes/invoice.$i'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const RestaurantIRoute = RestaurantIRouteImport.update({
  id: '/restaurant/$i',
  path: '/restaurant/$i',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReviewsRoute = OwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNotificationsRoute = OwnerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMenuRoute = OwnerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCouponsRoute = OwnerCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerRoute,
} as any)
const InvoiceIRoute = InvoiceIRouteImport.update({
  id: '/invoice/$i',
  path: '/invoice/$i',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/invoices': typeof InvoicesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/track': typeof TrackRoute
  '/invoice/$i': typeof InvoiceIRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/coupons': typeof OwnerCouponsRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/restaurant/$i': typeof RestaurantIRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/invoices': typeof InvoicesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/track': typeof TrackRoute
  '/invoice/$i': typeof InvoiceIRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/coupons': typeof OwnerCouponsRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/restaurant/$i': typeof RestaurantIRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/invoices': typeof InvoicesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/track': typeof TrackRoute
  '/invoice/$i': typeof InvoiceIRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/coupons': typeof OwnerCouponsRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/restaurant/$i': typeof RestaurantIRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/cart'
    | '/favorites'
    | '/help'
    | '/home'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/owner'
    | '/payments'
    | '/profile'
    | '/track'
    | '/invoice/$i'
    | '/owner/analytics'
    | '/owner/coupons'
    | '/owner/menu'
    | '/owner/notifications'
    | '/owner/orders'
    | '/owner/reviews'
    | '/owner/settings'
    | '/restaurant/$i'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/cart'
    | '/favorites'
    | '/help'
    | '/home'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/track'
    | '/invoice/$i'
    | '/owner/analytics'
    | '/owner/coupons'
    | '/owner/menu'
    | '/owner/notifications'
    | '/owner/orders'
    | '/owner/reviews'
    | '/owner/settings'
    | '/restaurant/$i'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/cart'
    | '/favorites'
    | '/help'
    | '/home'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/owner'
    | '/payments'
    | '/profile'
    | '/track'
    | '/invoice/$i'
    | '/owner/analytics'
    | '/owner/coupons'
    | '/owner/menu'
    | '/owner/notifications'
    | '/owner/orders'
    | '/owner/reviews'
    | '/owner/settings'
    | '/restaurant/$i'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  CartRoute: typeof CartRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  InvoicesRoute: typeof InvoicesRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  TrackRoute: typeof TrackRoute
  InvoiceIRoute: typeof InvoiceIRoute
  RestaurantIRoute: typeof RestaurantIRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/restaurant/$i': {
      id: '/restaurant/$i'
      path: '/restaurant/$i'
      fullPath: '/restaurant/$i'
      preLoaderRoute: typeof RestaurantIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reviews': {
      id: '/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof OwnerReviewsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/notifications': {
      id: '/owner/notifications'
      path: '/notifications'
      fullPath: '/owner/notifications'
      preLoaderRoute: typeof OwnerNotificationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/menu': {
      id: '/owner/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerMenuRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/coupons': {
      id: '/owner/coupons'
      path: '/coupons'
      fullPath: '/owner/coupons'
      preLoaderRoute: typeof OwnerCouponsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/invoice/$i': {
      id: '/invoice/$i'
      path: '/invoice/$i'
      fullPath: '/invoice/$i'
      preLoaderRoute: typeof InvoiceIRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OwnerRouteChildren {
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerCouponsRoute: typeof OwnerCouponsRoute
  OwnerMenuRoute: typeof OwnerMenuRoute
  OwnerNotificationsRoute: typeof OwnerNotificationsRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerReviewsRoute: typeof OwnerReviewsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerCouponsRoute: OwnerCouponsRoute,
  OwnerMenuRoute: OwnerMenuRoute,
  OwnerNotificationsRoute: OwnerNotificationsRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerReviewsRoute: OwnerReviewsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  CartRoute: CartRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  InvoicesRoute: InvoicesRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  TrackRoute: TrackRoute,
  InvoiceIRoute: InvoiceIRoute,
  RestaurantIRoute: RestaurantIRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
