/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as OwnerMenuRouteImport } from './routes/owner.menu'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMenuRoute = OwnerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/track': typeof TrackRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/track': typeof TrackRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/owner': typeof OwnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/track': typeof TrackRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/cart'
    | '/favorites'
    | '/help'
    | '/home'
    | '/notifications'
    | '/orders'
    | '/owner'
    | '/payments'
    | '/profile'
    | '/track'
    | '/owner/menu'
    | '/owner/orders'
    | '/owner/settings'
    | '/restaurant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/cart'
    | '/favorites'
    | '/help'
    | '/home'
    | '/notifications'
    | '/orders'
    | '/owner'
    | '/payments'
    | '/profile'
    | '/track'
    | '/owner/menu'
    | '/owner/orders'
    | '/owner/settings'
    | '/restaurant/$id'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/cart'
    | '/favorites'
    | '/help'
    | '/home'
    | '/notifications'
    | '/orders'
    | '/owner'
    | '/payments'
    | '/profile'
    | '/track'
    | '/owner/menu'
    | '/owner/orders'
    | '/owner/settings'
    | '/restaurant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  CartRoute: typeof CartRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  TrackRoute: typeof TrackRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/menu': {
      id: '/owner/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerMenuRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerMenuRoute: typeof OwnerMenuRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerMenuRoute: OwnerMenuRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  CartRoute: CartRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  TrackRoute: TrackRoute,
  RestaurantIdRoute: RestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
